### PR TITLE
Add support for configuration persistance.

### LINKED ISSUE #8: User configuration sync issue with gcs-storage branch dockerfile
Hi @adiroiban ,

I built docker image from gcs-storage branch Dockerfile. I integrated with GCS bucket but when I create user through admin panel and tries to login with that user getting below error and also I noticed there is no user folder created under /srv/storage(even default test_user mentioned in that docker image).

```
2021-10-17T08:17:48+00:00 20137 single-server-uuid Unknown 10.4.0.1:5746 Account "test" of type "application" from "DEFAULT_GROUP", authenticated as "test" by "SFTPPlus Accounts and Administrators" of type "application" using password.
2021-10-17T08:17:48+00:00 20067 Process test 10.4.0.1:5746 Failed to get home folder for account. OS_HOME folder can only be used for OS accounts.
2021-10-17T08:17:48+00:00 40000 https-1 Unknown 10.4.0.1:5746 Unauthorized request for "/__chsps__/login". See previous event.
```
But when I create a test folder under the mount point /srv/storage its syncing with GCS. 

Below is the manifests I am using to deploy into kubernetes

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sftpplus-app
  name: sftpplus-app
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sftpplus-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sftpplus-app
    spec:
      containers:
      - env:
        - name: GCS_BUCKET
          value: test_bucket
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /srv/gcs-credentials/gcs-credentials.json
        image: sftpplus
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command: ["fusermount", "-u", "/srv/storage"]
        name: sftpplus-trial
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /srv/gcs-credentials
          name: gcs-credentials-key
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: gcs-credentials-key
        secret:
          defaultMode: 420
          secretName: sftpplus.gcs.credentials
```

I was able to mount GCS but I got some warnings while deploying into pod.

```
2021/10/17 07:52:41.961994 Using mount point: /srv/storage
2021/10/17 07:52:42.090501 Opening GCS connection...
2021/10/17 07:52:43.044830 Mounting file system "test"...
2021/10/17 07:52:43.107034 File system has been successfully mounted.
S3 Cloud storage disabled
Configuration directory already initialized.
Starting using configuration from: /opt/sftpplus/configuration
2021-10-17T07:52:52+00:00 20186 single-server-uuid Process 0.0.0.0:0 You are using the evaluation version. Email us at sales@proatria.com or visit https://www.sftpplus.com/pricing/ to get the full licence. The demo expires in 98 day(s).
2021-10-17T07:52:52+00:00 20001 single-server-uuid Process 0.0.0.0:0 Starting SFTPPlus TRIAL - 4.14.0+trial.
2021-10-17T07:52:52+00:00 20072 single-server-uuid Process 0.0.0.0:0 Cryptography: OpenSSL 1.1.1f  31 Mar 2020 (269488239). Privileges: root capabilities disabled.
2021-10-17T07:52:52+00:00 20070 single-server-uuid Process 0.0.0.0:0 Missing user impersonation capabilities. Server can not authenticate operating system accounts.
2021-10-17T07:52:52+00:00 20073 single-server-uuid Process 0.0.0.0:0 Missing capabilities for creating missing local home folders.
```

### PR DESCRIPTION
**Pull request by adiroiban**
Scope
=====

Fixes #8

The trial container is nice, but it has no persistence.

Also, the seed configuration is old.

Also, the image is built with static private key... which is bad.
The private key should be generated at run-time, if no config exits.

Changes
=======

Add support to load the config from a different directory.
In this way, you can mount a volume with the config and inject your persistance.

Refactor the image setup and entrypoint to generate the SSH/SSL key at runtime.
Without this, multiple people could use the image and user the same private key.

The config file was updated for latest changes.

Add support for Ubuntu 22.04

I have already pushed proatria/sftpplus-trial:latest based on this image as trial was not updated in the last 5 months.

How to test
==========

reviewers: @dumol 

I plan to use this for a K8s deployment demo.

There is test.sh script that will build the image and spin a container.

### CODE REVIEW

**Comment by adiroiban** [comment]
@dumol I have start this PR, but I will need help from you to polish the script and add support for alpine and rhel for gcs-fuse and s3fs.

I have used the current code as an experiment for deploying SFTPPlus in kubernetes - https://github.com/proatria/sftpplus-kubernetes

Thanks!

**Comment by dumol** [comment]
The simplest way to enable persistence is already documented in the README. True, it's not automated, but I don't think it should be if we are to keep things simple and easy to understand.

In this regard, I feel this is becoming too complicated for someone trying SFTPPlus and Docker for the first time. Unless they are already fluent in Docker, S3, GCFS, etc. Do we target these techies now?

I assumed this is a repo for someone somewhat familiar with SFTPPlus to see how to start using it under Docker. I feel this is the more important group to target here. The advanced techies would know how to integrate SFTPPlus under  Docker with their cloud-based filesystem of choice once you show them the basics of containerizing SFTPPlus.

**Comment by adiroiban** [comment]
I think that the trend is to stop using local Docker servers, and use kubernetes cluster or independent containers like Cloud Run

For those environments local volumes are not available ... and I don't think that in these days people are using local volumes for production usage.

But now we also have an https://github.com/proatria/sftpplus-kubernetes repo, so we can keep this repo super simple
and add the more complex configuration in the kubernetes repo

i will think about it

**Comment by dumol** [comment]
OK, thanks!

As discussed on #chevah yesterday, I would strongly prefer to keep this simple, for instruction purposes.

**Comment by adiroiban** [comment]
@dumol please take a look.

With latest Ubuntu/Linux, we no longer need openssl ... but I will leave that change for another PR.

needs-review

**Review by dumol — APPROVED** [review]
Looks fine, works fine!

Just some minor improvements for image/container cleanup for `test.sh` in my commit above. Please review and feel free to only keep what you think it's suitable. Thanks!

**Comment by adiroiban** [comment]
Thanks for the review.

I think that we need some sort of automated tested to make sure we can build and run the images. I can see what I can do.

First I will try to use the image in our on-prem k8s cluster

**Comment by adiroiban** [comment]
CI tests added. The tests were written using bash + unix tools. Should be good enough for sysadmins.

**Pull request merged**
